// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6ayXsyZXLiswpciCGlZKsdBJ84ZdaGk',
    appId: '1:506963583317:web:12916a355e5c47d50e0fdc',
    messagingSenderId: '506963583317',
    projectId: 'cooking-recipes-28558',
    authDomain: 'cooking-recipes-28558.firebaseapp.com',
    storageBucket: 'cooking-recipes-28558.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb0hW6c7A40qY9yX2_hbpSEVASej-v0jU',
    appId: '1:506963583317:android:e06da9e351be3b340e0fdc',
    messagingSenderId: '506963583317',
    projectId: 'cooking-recipes-28558',
    storageBucket: 'cooking-recipes-28558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7GlGAz6JejzopwUN4HMREF5NCq7iF7o',
    appId: '1:506963583317:ios:dc7d5c294d6331310e0fdc',
    messagingSenderId: '506963583317',
    projectId: 'cooking-recipes-28558',
    storageBucket: 'cooking-recipes-28558.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7GlGAz6JejzopwUN4HMREF5NCq7iF7o',
    appId: '1:506963583317:ios:dc7d5c294d6331310e0fdc',
    messagingSenderId: '506963583317',
    projectId: 'cooking-recipes-28558',
    storageBucket: 'cooking-recipes-28558.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTeste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc6ayXsyZXLiswpciCGlZKsdBJ84ZdaGk',
    appId: '1:506963583317:web:5b39832a85e6c8b90e0fdc',
    messagingSenderId: '506963583317',
    projectId: 'cooking-recipes-28558',
    authDomain: 'cooking-recipes-28558.firebaseapp.com',
    storageBucket: 'cooking-recipes-28558.firebasestorage.app',
  );
}
